### ISSUE TITLE
Installation part missing in documentation

### ISSUE THREAD

**Issue by AntonTrapp** [crbelaus/trans#59]
Major issue 😄 

Something like:

add `{:trans, "~> 2.0"}` to deps in mix.exs

is missing. Just noticed it because I wanted to copy/paste it and I'm very lazy 😏

**Comment by crbelaus** [comment]
I've deliberately omitted this part in the documentation since [it is already provided by hex.pm][1], which sould be the main entrypoint of the library. From there you can access this repository as well as [the documentation][2].

Thank you very much for your suggestion @AntonTrapp :clap: 

[1]: https://hex.pm/packages/trans
[2]: https://hexdocs.pm/trans/
