### ISSUE TITLE
Integration with ElasticSearch

### ISSUE THREAD

**Issue by andresgutgon** [crbelaus/trans#61]
Hi, first thanks for the project, looks amaizing. I'm considering using in a pet project. In this pet project I would also like to try ElasticSearch. 

My question is if someone has indexed in elastic search translated fields with trans.

Thanks and sorry if it's already covered in docs, I did not see nothing related.

**Comment by crbelaus** [comment]
I've never used ElasticSearch myself, so integration with it is out of scope for Trans at the moment. 

This doesn't mean that the integration can not be done. Any pull request will be more than welcome. I am closing this issue since it won't be adressed by core developers of the project.

In any case, thank you very much for your suggestion @andresgutgon! :hugs:
